# Minecraft Lanterna Theme Properties
com.googlecode.lanterna.gui2.Borders$SingleLine.char[HORIZONTAL_LINE] = \u2500
com.googlecode.lanterna.gui2.Borders$SingleLine.char[VERTICAL_LINE] = \u2502
com.googlecode.lanterna.gui2.Borders$SingleLine.char[BOTTOM_LEFT_CORNER] = \u2514
com.googlecode.lanterna.gui2.Borders$SingleLine.char[TOP_LEFT_CORNER] = \u250c
com.googlecode.lanterna.gui2.Borders$SingleLine.char[BOTTOM_RIGHT_CORNER] = \u2518
com.googlecode.lanterna.gui2.Borders$SingleLine.char[TOP_RIGHT_CORNER] = \u2510

# Button
com.googlecode.lanterna.gui2.Button.foreground = white
com.googlecode.lanterna.gui2.Button.background = black
com.googlecode.lanterna.gui2.Button.foreground[PRELIGHT] = yellow
com.googlecode.lanterna.gui2.Button.background[PRELIGHT] = black
com.googlecode.lanterna.gui2.Button.sgr[PRELIGHT] = bold
com.googlecode.lanterna.gui2.Button.foreground[ACTIVE] = yellow
com.googlecode.lanterna.gui2.Button.background[ACTIVE] = black
com.googlecode.lanterna.gui2.Button.sgr[ACTIVE] = bold
com.googlecode.lanterna.gui2.Button.foreground[SELECTED] = green
com.googlecode.lanterna.gui2.Button.background[SELECTED] = black
com.googlecode.lanterna.gui2.Button.sgr[SELECTED] = bold
com.googlecode.lanterna.gui2.Button.char[LEFT_BORDER] = [
com.googlecode.lanterna.gui2.Button.char[RIGHT_BORDER] = ]

# ComboBox
com.googlecode.lanterna.gui2.ComboBox.foreground = white
com.googlecode.lanterna.gui2.ComboBox.background = black
com.googlecode.lanterna.gui2.ComboBox.foreground[ACTIVE] = yellow
com.googlecode.lanterna.gui2.ComboBox.background[ACTIVE] = black
com.googlecode.lanterna.gui2.ComboBox.foreground[SELECTED] = yellow
com.googlecode.lanterna.gui2.ComboBox.background[SELECTED] = black
com.googlecode.lanterna.gui2.ComboBox.char[POPUP] = \u25bc

# CheckBox
com.googlecode.lanterna.gui2.CheckBox.foreground = white
com.googlecode.lanterna.gui2.CheckBox.background = black
com.googlecode.lanterna.gui2.CheckBox.foreground[SELECTED] = yellow
com.googlecode.lanterna.gui2.CheckBox.background[SELECTED] = black
com.googlecode.lanterna.gui2.CheckBox.char[MARKER] = x

# Window Decoration
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.foreground[ACTIVE] = green
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.background[ACTIVE] = black
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.sgr[ACTIVE] = bold
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.char[HORIZONTAL_LINE] = \u2550
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.char[VERTICAL_LINE] = \u2551
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.char[BOTTOM_LEFT_CORNER] = \u255a
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.char[TOP_LEFT_CORNER] = \u2554
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.char[BOTTOM_RIGHT_CORNER] = \u255d
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.char[TOP_RIGHT_CORNER] = \u2557
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.property[CENTER_TITLE] = true
com.googlecode.lanterna.gui2.DefaultWindowDecorationRenderer.property[TITLE_PADDING] = true

# GUI Backdrop
com.googlecode.lanterna.gui2.GUIBackdrop.foreground = green
com.googlecode.lanterna.gui2.GUIBackdrop.background = black

# TextBox
com.googlecode.lanterna.gui2.TextBox.foreground = white
com.googlecode.lanterna.gui2.TextBox.background = black
com.googlecode.lanterna.gui2.TextBox.foreground[SELECTED] = white
com.googlecode.lanterna.gui2.TextBox.background[SELECTED] = black

# ActionListBox
com.googlecode.lanterna.gui2.AbstractListBox.foreground = white
com.googlecode.lanterna.gui2.AbstractListBox.background = black
com.googlecode.lanterna.gui2.AbstractListBox.foreground[SELECTED] = yellow
com.googlecode.lanterna.gui2.AbstractListBox.background[SELECTED] = black
com.googlecode.lanterna.gui2.AbstractListBox.sgr[SELECTED] = bold

# Table
com.googlecode.lanterna.gui2.table.Table.foreground = white
com.googlecode.lanterna.gui2.table.Table.background = black
com.googlecode.lanterna.gui2.table.Table.foreground[SELECTED] = yellow
com.googlecode.lanterna.gui2.table.Table.background[SELECTED] = black
com.googlecode.lanterna.gui2.table.Table.sgr[SELECTED] = bold
com.googlecode.lanterna.gui2.table.Table.sgr[HEADER] = bold
